name = "NODEDynamics"
uuid = "57723ca8-2715-4bf2-a8d0-05a37925b76f"
authors = ["Sven Duve <svenduve@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
